import type { TexturePathInfo } from '@/types/texture'

const item = (path: string, label: string, w = 16, h = 16): TexturePathInfo =>
  ({ path: `assets/minecraft/textures/item/${path}`, label, category: 'item', defaultWidth: w, defaultHeight: h })

const block = (path: string, label: string, w = 16, h = 16, animatable = false): TexturePathInfo =>
  ({ path: `assets/minecraft/textures/block/${path}`, label, category: 'block', defaultWidth: w, defaultHeight: h, animatable })

const gui = (path: string, label: string, w = 256, h = 256): TexturePathInfo =>
  ({ path: `assets/minecraft/textures/gui/${path}`, label, category: 'gui', defaultWidth: w, defaultHeight: h })

const hud = (path: string, label: string, w = 16, h = 16): TexturePathInfo =>
  ({ path: `assets/minecraft/textures/gui/${path}`, label, category: 'hud', defaultWidth: w, defaultHeight: h })

export const TEXTURE_PATHS: TexturePathInfo[] = [

  // ══ ITEMS ══════════════════════════════════════════════════════════════════

  // 검
  item('wooden_sword.png',      '나무 검'),
  item('stone_sword.png',       '돌 검'),
  item('iron_sword.png',        '철 검'),
  item('golden_sword.png',      '금 검'),
  item('diamond_sword.png',     '다이아몬드 검'),
  item('netherite_sword.png',   '네더라이트 검'),

  // 곡괭이
  item('wooden_pickaxe.png',    '나무 곡괭이'),
  item('stone_pickaxe.png',     '돌 곡괭이'),
  item('iron_pickaxe.png',      '철 곡괭이'),
  item('golden_pickaxe.png',    '금 곡괭이'),
  item('diamond_pickaxe.png',   '다이아몬드 곡괭이'),
  item('netherite_pickaxe.png', '네더라이트 곡괭이'),

  // 도끼
  item('wooden_axe.png',        '나무 도끼'),
  item('stone_axe.png',         '돌 도끼'),
  item('iron_axe.png',          '철 도끼'),
  item('golden_axe.png',        '금 도끼'),
  item('diamond_axe.png',       '다이아몬드 도끼'),
  item('netherite_axe.png',     '네더라이트 도끼'),

  // 삽
  item('wooden_shovel.png',     '나무 삽'),
  item('stone_shovel.png',      '돌 삽'),
  item('iron_shovel.png',       '철 삽'),
  item('golden_shovel.png',     '금 삽'),
  item('diamond_shovel.png',    '다이아몬드 삽'),
  item('netherite_shovel.png',  '네더라이트 삽'),

  // 괭이
  item('wooden_hoe.png',        '나무 괭이'),
  item('stone_hoe.png',         '돌 괭이'),
  item('iron_hoe.png',          '철 괭이'),
  item('golden_hoe.png',        '금 괭이'),
  item('diamond_hoe.png',       '다이아몬드 괭이'),
  item('netherite_hoe.png',     '네더라이트 괭이'),

  // 갑옷 — 헬멧
  item('leather_helmet.png',    '가죽 헬멧'),
  item('chainmail_helmet.png',  '사슬 헬멧'),
  item('iron_helmet.png',       '철 헬멧'),
  item('golden_helmet.png',     '금 헬멧'),
  item('diamond_helmet.png',    '다이아몬드 헬멧'),
  item('netherite_helmet.png',  '네더라이트 헬멧'),

  // 갑옷 — 흉갑
  item('leather_chestplate.png',   '가죽 흉갑'),
  item('chainmail_chestplate.png', '사슬 흉갑'),
  item('iron_chestplate.png',      '철 흉갑'),
  item('golden_chestplate.png',    '금 흉갑'),
  item('diamond_chestplate.png',   '다이아몬드 흉갑'),
  item('netherite_chestplate.png', '네더라이트 흉갑'),

  // 갑옷 — 레깅스
  item('leather_leggings.png',   '가죽 레깅스'),
  item('chainmail_leggings.png', '사슬 레깅스'),
  item('iron_leggings.png',      '철 레깅스'),
  item('golden_leggings.png',    '금 레깅스'),
  item('diamond_leggings.png',   '다이아몬드 레깅스'),
  item('netherite_leggings.png', '네더라이트 레깅스'),

  // 갑옷 — 부츠
  item('leather_boots.png',   '가죽 부츠'),
  item('chainmail_boots.png', '사슬 부츠'),
  item('iron_boots.png',      '철 부츠'),
  item('golden_boots.png',    '금 부츠'),
  item('diamond_boots.png',   '다이아몬드 부츠'),
  item('netherite_boots.png', '네더라이트 부츠'),

  // 활·화살
  item('bow.png',               '활'),
  item('crossbow_standby.png',   '석궁'),
  item('arrow.png',             '화살'),
  item('spectral_arrow.png',    '유령 화살'),
  item('tipped_arrow_base.png', '효과 화살'),
  item('trident.png',           '삼지창'),

  // 음식
  item('apple.png',             '사과'),
  item('golden_apple.png',      '황금 사과'),
  item('bread.png',             '빵'),
  item('beef.png',              '날 소고기'),
  item('cooked_beef.png',       '스테이크'),
  item('porkchop.png',          '날 돼지고기'),
  item('cooked_porkchop.png',   '구운 돼지고기'),
  item('chicken.png',           '날 닭고기'),
  item('cooked_chicken.png',    '구운 닭고기'),
  item('cod.png',               '날 대구'),
  item('cooked_cod.png',        '구운 대구'),
  item('salmon.png',            '날 연어'),
  item('cooked_salmon.png',     '구운 연어'),
  item('carrot.png',            '당근'),
  item('golden_carrot.png',     '황금 당근'),
  item('potato.png',            '감자'),
  item('baked_potato.png',      '구운 감자'),
  item('poisonous_potato.png',  '독 감자'),
  item('melon_slice.png',       '수박 조각'),
  item('glistering_melon_slice.png', '빛나는 수박'),
  item('pumpkin_pie.png',       '호박 파이'),
  item('cookie.png',            '쿠키'),
  item('cake.png',              '케이크'),
  item('mushroom_stew.png',     '버섯 스튜'),
  item('beetroot.png',          '비트'),
  item('beetroot_soup.png',     '비트 수프'),
  item('sweet_berries.png',     '달콤한 열매'),
  item('honey_bottle.png',      '꿀병'),

  // 광물·재료
  item('diamond.png',           '다이아몬드'),
  item('emerald.png',           '에메랄드'),
  item('gold_ingot.png',        '금 주괴'),
  item('iron_ingot.png',        '철 주괴'),
  item('netherite_ingot.png',   '네더라이트 주괴'),
  item('netherite_scrap.png',   '네더라이트 파편'),
  item('coal.png',              '석탄'),
  item('charcoal.png',          '숯'),
  item('quartz.png',            '네더 석영'),
  item('lapis_lazuli.png',      '청금석'),
  item('redstone.png',          '레드스톤'),
  item('raw_iron.png',          '원석 철'),
  item('raw_gold.png',          '원석 금'),
  item('raw_copper.png',        '원석 구리'),
  item('copper_ingot.png',      '구리 주괴'),
  item('amethyst_shard.png',    '자수정 파편'),

  // 마법·유틸
  item('stick.png',             '막대기'),
  item('string.png',            '실'),
  item('feather.png',           '깃털'),
  item('flint.png',             '부싯돌'),
  item('flint_and_steel.png',   '부싯돌과 부시'),
  item('shears.png',            '가위'),
  item('fishing_rod.png',       '낚싯대'),
  item('compass_00.png',        '나침반'),
  item('clock_00.png',          '시계'),
  item('map.png',               '지도'),
  item('filled_map.png',        '채워진 지도'),
  item('book.png',              '책'),
  item('written_book.png',      '쓰인 책'),
  item('enchanted_book.png',    '마법책'),
  item('writable_book.png',     '쓸 수 있는 책'),
  item('glass_bottle.png',      '유리병'),
  item('potion.png',            '물약'),
  item('splash_potion.png',     '투척용 물약'),
  item('lingering_potion.png',  '잔류 물약'),
  item('bucket.png',            '양동이'),
  item('water_bucket.png',      '물 양동이'),
  item('lava_bucket.png',       '용암 양동이'),
  item('milk_bucket.png',       '우유 양동이'),
  item('powder_snow_bucket.png','가루 눈 양동이'),
  item('ender_pearl.png',       '엔더 진주'),
  item('ender_eye.png',         '엔더의 눈'),
  item('blaze_rod.png',         '블레이즈 막대기'),
  item('blaze_powder.png',      '블레이즈 가루'),
  item('magma_cream.png',       '마그마 크림'),
  item('slime_ball.png',        '슬라임 공'),
  item('ghast_tear.png',        '가스트의 눈물'),
  item('spider_eye.png',        '거미 눈'),
  item('fermented_spider_eye.png', '발효된 거미 눈'),
  item('nether_star.png',       '네더 별'),
  item('totem_of_undying.png',  '불사의 토템'),
  item('elytra.png',            '겉날개'),
  item('lead.png',              '줄'),
  item('name_tag.png',          '이름표'),
  item('saddle.png',            '안장'),
  item('bone.png',              '뼈'),
  item('bone_meal.png',         '뼛가루'),
  item('ink_sac.png',           '먹물 주머니'),
  item('glow_ink_sac.png',      '빛나는 먹물 주머니'),
  item('gunpowder.png',         '화약'),
  item('fire_charge.png',       '화염구'),
  item('snowball.png',          '눈덩이'),
  item('egg.png',               '달걀'),
  item('turtle_egg.png',        '거북이 알'),
  item('turtle_helmet.png',     '거북이 헬멧'),
  item('heart_of_the_sea.png',  '바다의 심장'),
  item('nautilus_shell.png',    '앵무조개 껍데기'),
  item('prismarine_crystals.png','프리즈머린 수정'),
  item('prismarine_shard.png',  '프리즈머린 파편'),
  item('phantom_membrane.png',  '팬텀 막'),
  item('dragon_breath.png',     '용의 숨결'),
  item('experience_bottle.png', '경험치 병'),
  item('end_crystal.png',       '엔드 수정'),
  item('chorus_fruit.png',      '코러스 열매'),
  item('popped_chorus_fruit.png','터진 코러스 열매'),
  item('shulker_shell.png',     '쉘커 껍데기'),
  item('rabbit_foot.png',       '토끼 발'),
  item('rabbit_hide.png',       '토끼 가죽'),

  // 음반
  item('music_disc_13.png',     '음반 13'),
  item('music_disc_cat.png',    '음반 Cat'),
  item('music_disc_blocks.png', '음반 Blocks'),
  item('music_disc_chirp.png',  '음반 Chirp'),
  item('music_disc_far.png',    '음반 Far'),
  item('music_disc_mall.png',   '음반 Mall'),
  item('music_disc_mellohi.png','음반 Mellohi'),
  item('music_disc_stal.png',   '음반 Stal'),
  item('music_disc_strad.png',  '음반 Strad'),
  item('music_disc_ward.png',   '음반 Ward'),
  item('music_disc_11.png',     '음반 11'),
  item('music_disc_wait.png',   '음반 Wait'),
  item('music_disc_pigstep.png','음반 Pigstep'),
  item('music_disc_otherside.png','음반 Otherside'),
  item('disc_fragment_5.png',   '음반 조각 5'),

  // ══ BLOCKS ═════════════════════════════════════════════════════════════════

  // 기본 지형
  block('grass_block_top.png',  '잔디 블록 (윗면)'),
  block('grass_block_side.png', '잔디 블록 (옆면)'),
  block('dirt.png',             '흙'),
  block('coarse_dirt.png',      '거친 흙'),
  block('podzol_top.png',       '포드졸 (윗면)'),
  block('podzol_side.png',      '포드졸 (옆면)'),
  block('mycelium_top.png',     '균사 (윗면)'),
  block('mycelium_side.png',    '균사 (옆면)'),
  block('stone.png',            '돌'),
  block('cobblestone.png',      '조약돌'),
  block('mossy_cobblestone.png','이끼 낀 조약돌'),
  block('gravel.png',           '자갈'),
  block('sand.png',             '모래'),
  block('red_sand.png',         '붉은 모래'),
  block('sandstone_top.png',    '사암 (윗면)'),
  block('sandstone.png',        '사암 (옆면)'),
  block('sandstone_bottom.png', '사암 (아랫면)'),
  block('red_sandstone_top.png','붉은 사암 (윗면)'),
  block('red_sandstone.png',    '붉은 사암 (옆면)'),
  block('bedrock.png',          '베드락'),
  block('clay.png',             '점토'),
  block('snow.png',             '눈'),
  block('ice.png',              '얼음'),
  block('packed_ice.png',       '단단한 얼음'),
  block('blue_ice.png',         '청색 얼음'),

  // 광석
  block('coal_ore.png',         '석탄 광석'),
  block('iron_ore.png',         '철 광석'),
  block('copper_ore.png',       '구리 광석'),
  block('gold_ore.png',         '금 광석'),
  block('redstone_ore.png',     '레드스톤 광석'),
  block('lapis_ore.png',        '청금석 광석'),
  block('diamond_ore.png',      '다이아몬드 광석'),
  block('emerald_ore.png',      '에메랄드 광석'),
  block('nether_gold_ore.png',  '네더 금 광석'),
  block('nether_quartz_ore.png','네더 석영 광석'),
  block('deepslate_coal_ore.png',    '심층암 석탄 광석'),
  block('deepslate_iron_ore.png',    '심층암 철 광석'),
  block('deepslate_copper_ore.png',  '심층암 구리 광석'),
  block('deepslate_gold_ore.png',    '심층암 금 광석'),
  block('deepslate_redstone_ore.png','심층암 레드스톤 광석'),
  block('deepslate_lapis_ore.png',   '심층암 청금석 광석'),
  block('deepslate_diamond_ore.png', '심층암 다이아몬드 광석'),
  block('deepslate_emerald_ore.png', '심층암 에메랄드 광석'),
  block('ancient_debris_top.png',    '고대 잔해 (윗면)'),
  block('ancient_debris_side.png',   '고대 잔해 (옆면)'),

  // 광물 블록
  block('coal_block.png',       '석탄 블록'),
  block('iron_block.png',       '철 블록'),
  block('copper_block.png',     '구리 블록'),
  block('gold_block.png',       '금 블록'),
  block('redstone_block.png',   '레드스톤 블록'),
  block('lapis_block.png',      '청금석 블록'),
  block('diamond_block.png',    '다이아몬드 블록'),
  block('emerald_block.png',    '에메랄드 블록'),
  block('netherite_block.png',  '네더라이트 블록'),
  block('amethyst_block.png',   '자수정 블록'),

  // 나무 (참나무)
  block('oak_log.png',          '참나무 원목 (옆면)'),
  block('oak_log_top.png',      '참나무 원목 (윗면)'),
  block('oak_planks.png',       '참나무 판자'),
  block('oak_leaves.png',       '참나무 잎'),

  // 나무 (가문비)
  block('spruce_log.png',       '가문비나무 원목 (옆면)'),
  block('spruce_log_top.png',   '가문비나무 원목 (윗면)'),
  block('spruce_planks.png',    '가문비나무 판자'),
  block('spruce_leaves.png',    '가문비나무 잎'),

  // 나무 (자작)
  block('birch_log.png',        '자작나무 원목 (옆면)'),
  block('birch_log_top.png',    '자작나무 원목 (윗면)'),
  block('birch_planks.png',     '자작나무 판자'),
  block('birch_leaves.png',     '자작나무 잎'),

  // 나무 (정글)
  block('jungle_log.png',       '정글 원목 (옆면)'),
  block('jungle_log_top.png',   '정글 원목 (윗면)'),
  block('jungle_planks.png',    '정글 판자'),
  block('jungle_leaves.png',    '정글 잎'),

  // 나무 (아카시아)
  block('acacia_log.png',       '아카시아 원목 (옆면)'),
  block('acacia_log_top.png',   '아카시아 원목 (윗면)'),
  block('acacia_planks.png',    '아카시아 판자'),
  block('acacia_leaves.png',    '아카시아 잎'),

  // 나무 (짙은 참나무)
  block('dark_oak_log.png',     '짙은 참나무 원목 (옆면)'),
  block('dark_oak_log_top.png', '짙은 참나무 원목 (윗면)'),
  block('dark_oak_planks.png',  '짙은 참나무 판자'),
  block('dark_oak_leaves.png',  '짙은 참나무 잎'),

  // 나무 (맹그로브)
  block('mangrove_log.png',     '맹그로브 원목 (옆면)'),
  block('mangrove_log_top.png', '맹그로브 원목 (윗면)'),
  block('mangrove_planks.png',  '맹그로브 판자'),
  block('mangrove_leaves.png',  '맹그로브 잎'),

  // 나무 (체리)
  block('cherry_log.png',       '벚나무 원목 (옆면)'),
  block('cherry_log_top.png',   '벚나무 원목 (윗면)'),
  block('cherry_planks.png',    '벚나무 판자'),
  block('cherry_leaves.png',    '벚나무 잎'),

  // 돌 계열
  block('granite.png',          '화강암'),
  block('polished_granite.png', '연마된 화강암'),
  block('diorite.png',          '섬록암'),
  block('polished_diorite.png', '연마된 섬록암'),
  block('andesite.png',         '안산암'),
  block('polished_andesite.png','연마된 안산암'),
  block('calcite.png',          '방해석'),
  block('tuff.png',             '응회암'),
  block('deepslate.png',        '심층암'),
  block('cobbled_deepslate.png','조약돌 심층암'),
  block('polished_deepslate.png','연마된 심층암'),
  block('deepslate_bricks.png', '심층암 벽돌'),
  block('deepslate_tiles.png',  '심층암 타일'),
  block('stone_bricks.png',     '석재 벽돌'),
  block('mossy_stone_bricks.png','이끼 낀 석재 벽돌'),
  block('cracked_stone_bricks.png','균열된 석재 벽돌'),
  block('chiseled_stone_bricks.png','장식된 석재 벽돌'),
  block('bricks.png',           '벽돌'),

  // 네더
  block('netherrack.png',       '네더랙'),
  block('nether_bricks.png',    '네더 벽돌'),
  block('red_nether_bricks.png','붉은 네더 벽돌'),
  block('nether_wart_block.png','네더 사마귀 블록'),
  block('warped_wart_block.png','뒤틀린 사마귀 블록'),
  block('basalt_top.png',       '현무암 (윗면)'),
  block('basalt_side.png',      '현무암 (옆면)'),
  block('polished_basalt_top.png','연마된 현무암 (윗면)'),
  block('polished_basalt_side.png','연마된 현무암 (옆면)'),
  block('blackstone.png',       '흑석'),
  block('gilded_blackstone.png','금장 흑석'),
  block('soul_sand.png',        '소울 샌드'),
  block('soul_soil.png',        '소울 흙'),
  block('magma.png',            '마그마 블록'),
  block('obsidian.png',         '흑요석'),
  block('crying_obsidian.png',  '울부짖는 흑요석'),

  // 엔드
  block('end_stone.png',        '엔드 돌'),
  block('end_stone_bricks.png', '엔드 석재 벽돌'),
  block('purpur_block.png',     '퍼퍼 블록'),
  block('purpur_pillar.png',    '퍼퍼 기둥'),
  block('purpur_pillar_top.png','퍼퍼 기둥 (윗면)'),
  block('end_portal_frame_top.png','엔드 포탈 프레임 (윗면)'),
  block('end_portal_frame_side.png','엔드 포탈 프레임 (옆면)'),

  // 유리·빛
  block('glass.png',            '유리'),
  block('white_stained_glass.png', '흰색 유리'),
  block('orange_stained_glass.png','주황색 유리'),
  block('magenta_stained_glass.png','자홍색 유리'),
  block('light_blue_stained_glass.png','하늘색 유리'),
  block('yellow_stained_glass.png','노란색 유리'),
  block('lime_stained_glass.png','연두색 유리'),
  block('pink_stained_glass.png','분홍색 유리'),
  block('gray_stained_glass.png','회색 유리'),
  block('light_gray_stained_glass.png','밝은 회색 유리'),
  block('cyan_stained_glass.png','청록색 유리'),
  block('purple_stained_glass.png','보라색 유리'),
  block('blue_stained_glass.png','파란색 유리'),
  block('brown_stained_glass.png','갈색 유리'),
  block('green_stained_glass.png','초록색 유리'),
  block('red_stained_glass.png','붉은색 유리'),
  block('black_stained_glass.png','검정색 유리'),
  block('glowstone.png',        '글로우스톤'),
  block('sea_lantern.png',      '바다 랜턴'),
  block('shroomlight.png',      '버섯빛'),
  block('lantern.png',          '랜턴'),
  block('soul_lantern.png',     '소울 랜턴'),
  block('torch.png',            '횃불'),

  // 양털
  block('white_wool.png',       '흰색 양털'),
  block('orange_wool.png',      '주황색 양털'),
  block('magenta_wool.png',     '자홍색 양털'),
  block('light_blue_wool.png',  '하늘색 양털'),
  block('yellow_wool.png',      '노란색 양털'),
  block('lime_wool.png',        '연두색 양털'),
  block('pink_wool.png',        '분홍색 양털'),
  block('gray_wool.png',        '회색 양털'),
  block('light_gray_wool.png',  '밝은 회색 양털'),
  block('cyan_wool.png',        '청록색 양털'),
  block('purple_wool.png',      '보라색 양털'),
  block('blue_wool.png',        '파란색 양털'),
  block('brown_wool.png',       '갈색 양털'),
  block('green_wool.png',       '초록색 양털'),
  block('red_wool.png',         '붉은색 양털'),
  block('black_wool.png',       '검정색 양털'),

  // 콘크리트
  block('white_concrete.png',   '흰색 콘크리트'),
  block('orange_concrete.png',  '주황색 콘크리트'),
  block('magenta_concrete.png', '자홍색 콘크리트'),
  block('light_blue_concrete.png','하늘색 콘크리트'),
  block('yellow_concrete.png',  '노란색 콘크리트'),
  block('lime_concrete.png',    '연두색 콘크리트'),
  block('pink_concrete.png',    '분홍색 콘크리트'),
  block('gray_concrete.png',    '회색 콘크리트'),
  block('light_gray_concrete.png','밝은 회색 콘크리트'),
  block('cyan_concrete.png',    '청록색 콘크리트'),
  block('purple_concrete.png',  '보라색 콘크리트'),
  block('blue_concrete.png',    '파란색 콘크리트'),
  block('brown_concrete.png',   '갈색 콘크리트'),
  block('green_concrete.png',   '초록색 콘크리트'),
  block('red_concrete.png',     '붉은색 콘크리트'),
  block('black_concrete.png',   '검정색 콘크리트'),

  // 테라코타
  block('terracotta.png',       '테라코타'),
  block('white_terracotta.png', '흰색 테라코타'),
  block('orange_terracotta.png','주황색 테라코타'),
  block('yellow_terracotta.png','노란색 테라코타'),
  block('red_terracotta.png',   '붉은색 테라코타'),
  block('brown_terracotta.png', '갈색 테라코타'),

  // 식물·꽃
  block('short_grass.png',      '풀'),
  block('fern.png',             '양치식물'),
  block('dead_bush.png',        '고사한 덤불'),
  block('dandelion.png',        '민들레'),
  block('poppy.png',            '양귀비'),
  block('blue_orchid.png',      '파란 난초'),
  block('allium.png',           '알리움'),
  block('azure_bluet.png',      '하늘색 꽃'),
  block('red_tulip.png',        '붉은 튤립'),
  block('orange_tulip.png',     '주황색 튤립'),
  block('white_tulip.png',      '흰색 튤립'),
  block('pink_tulip.png',       '분홍색 튤립'),
  block('oxeye_daisy.png',      '옥스아이 데이지'),
  block('cornflower.png',       '수레국화'),
  block('lily_of_the_valley.png','은방울꽃'),
  block('wither_rose.png',      '시든 장미'),
  block('sunflower_top.png',    '해바라기 (위)'),
  block('sunflower_bottom.png', '해바라기 (아래)'),
  block('cactus_side.png',      '선인장 (옆면)'),
  block('cactus_top.png',       '선인장 (윗면)'),
  block('sugar_cane.png',       '사탕수수'),
  block('vine.png',             '덩굴'),
  block('lily_pad.png',         '수련잎'),
  block('sea_pickle.png',       '바다 오이'),
  block('kelp.png',             '다시마'),
  block('bamboo_stalk.png',     '대나무'),

  // 레드스톤
  block('crafting_table_top.png',   '작업대 (윗면)'),
  block('crafting_table_front.png', '작업대 (앞면)'),
  block('crafting_table_side.png',  '작업대 (옆면)'),
  block('furnace_front.png',        '용광로 (앞면)'),
  block('furnace_front_on.png',     '용광로 (가동 중)'),
  block('furnace_side.png',         '용광로 (옆면)'),
  block('furnace_top.png',          '용광로 (윗면)'),
  block('blast_furnace_front.png',  '고폭 용광로 (앞면)'),
  block('smoker_front.png',         '훈연기 (앞면)'),
  block('tnt_side.png',             'TNT (옆면)'),
  block('tnt_top.png',              'TNT (윗면)'),
  block('tnt_bottom.png',           'TNT (아랫면)'),
  block('bookshelf.png',            '책장'),
  block('jukebox_side.png',         '주크박스 (옆면)'),
  block('jukebox_top.png',          '주크박스 (윗면)'),
  block('note_block.png',           '음표 블록'),
  block('dispenser_front.png',      '발사기 (앞면)'),
  block('dropper_front.png',        '투하기 (앞면)'),
  block('observer_front.png',       '관측기 (앞면)'),
  block('piston_top.png',           '피스톤 (윗면)'),
  block('piston_side.png',          '피스톤 (옆면)'),
  block('piston_top_sticky.png',    '끈적이 피스톤'),
  block('redstone_lamp.png',        '레드스톤 램프'),
  block('redstone_lamp_on.png',     '레드스톤 램프 (켜짐)'),
  block('beacon.png',               '비콘'),
  block('conduit.png',              '전도체'),

  // 기타
  block('sponge.png',               '해면'),
  block('wet_sponge.png',           '젖은 해면'),
  block('hay_block_top.png',        '건초 블록 (윗면)'),
  block('hay_block_side.png',       '건초 블록 (옆면)'),
  block('honeycomb_block.png',      '벌집 블록'),
  block('honey_block_top.png',      '꿀 블록 (윗면)'),
  block('honey_block_side.png',     '꿀 블록 (옆면)'),
  block('slime_block.png',          '슬라임 블록'),
  block('melon_side.png',           '수박 (옆면)'),
  block('melon_top.png',            '수박 (윗면)'),
  block('pumpkin_side.png',         '호박 (옆면)'),
  block('pumpkin_top.png',          '호박 (윗면)'),
  block('carved_pumpkin.png',       '조각된 호박'),

  // 애니메이션
  block('lava_still.png',       '용암', 16, 16, true),
  block('water_still.png',      '물', 16, 16, true),
  block('fire_0.png',           '불', 16, 16, true),
  block('nether_portal.png',    '네더 포탈', 16, 16, true),

  // ══ GUI ════════════════════════════════════════════════════════════════════
  gui('container/inventory.png',      '인벤토리'),
  gui('container/crafting_table.png', '작업대'),
  gui('container/chest.png',          '상자'),
  gui('container/furnace.png',        '용광로'),
  gui('container/enchanting_table.png','마법 부여대'),
  gui('container/anvil.png',          '모루'),
  gui('container/brewing_stand.png',  '양조기'),
  gui('container/beacon.png',         '비콘'),
  gui('container/hopper.png',         '호퍼'),
  gui('container/dispenser.png',      '발사기'),

  // ══ HUD ════════════════════════════════════════════════════════════════════
  hud('hud/health_heart.png',  '체력 하트'),
  hud('hud/hunger_icon.png',   '배고픔 아이콘'),
  hud('widgets.png',           '핫바', 256, 256),
  hud('crosshair.png',         '조준선'),
]

export function getTexturesByCategory(category: string): TexturePathInfo[] {
  return TEXTURE_PATHS.filter(t => t.category === category)
}

export function getTextureByPath(path: string): TexturePathInfo | undefined {
  return TEXTURE_PATHS.find(t => t.path === path)
}
